package com.iwomi.nofiaPay.core.enums;

public enum OperationTypeEnum {
    AGENT_CASH_COLLECTION,
    AGENT_DIGITAL_COLLECTION_MOMO,
    AGENT_DIGITAL_COLLECTION_OM,
    SELF_SERVICE_OM,
    SELF_SERVICE_MOMO,
    MERCHANT_CASH,
    MERCHANT_DIGITAL_MOMO,
    MERCHANT_DIGITAL_OM,
    AGENT_TO_TELLER
}
