apiV1Prefix: /api/v1/nofia

spring:
  application:
    name: NOFIAPAY
  datasource: # db config seems not to be used
    url: jdbc:mysql://localhost:3306/nofia?serverTimezone=Africa/Douala
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
#      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: always
      schema: classpath:quartz/schema.sql
  cloud:
    openfeign:
      httpclient:
#        disable-ssl-validation: true
#        enabled: false
      okhttp:
        enabled: true

server:
  port: 8082

app:
  files:
    downloads: /home/projects-downloads/nofia

#springdoc:
#  swagger-ui:
#    path: /api/v1/nofia/docs-ui.html

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 2
    leaseExpirationDurationInSeconds: 5
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/  # where to register this client
    #    healthcheck: this causes an error check later
    #      enabled: true
    lease:
      duration: 5
    enabled: false  # false value disables discovery request.

externals:
  iwomi:
    apiKeys:
      momo: "6fa7e10d-6e8b-4403-a4be-a8d64589b893"
      om: "d199e96b-0ef4-4824-ad3b-9e10b07b6c67"
    apiSecrets:
      momo: "51a9aeb8-4711-4f95-93e9-01fe40bf8f65"
      om: "eb2a6803-447f-4be7-8db3-290c689167fc"
    username: "2039NOF605IWOPAY"
    password: "202409FIA27PAY9098"
  base-url:
    auth: http://localhost:8080/api/v1/auth
    iwomiPay: https://www.pay.iwomitechnologies.com/api/iwomipay_prodv1
    nomen: http://localhost:8081/api/SYSTEMCORE

logging:
  level:
    org:
      springframework:
        messaging: DEBUG
        web:
          socket:
            messaging: DEBUG

#    com.example.howtodoinjava: DEBUG
