apiV1Prefix: /api/v1/nofia

spring:
  application:
    name: NOFIAPAY
  datasource: # db config seems not to be used
    url: jdbc:mysql://localhost:3306/nofia?serverTimezone=Africa/Douala
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
#      ddl-auto: create-drop
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: always
      schema: classpath:quartz/schema.sql
  cloud:
    openfeign:
      httpclient:
#        disable-ssl-validation: true
#        enabled: false
      okhttp:
        enabled: true

server:
  port: 8082

app:
  files:
    downloads: /home/projects-downloads/nofia

#springdoc:
#  swagger-ui:
#    path: /api/v1/nofia/docs-ui.html

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 2
    leaseExpirationDurationInSeconds: 5
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/  # where to register this client
    #    healthcheck: this causes an error check later
    #      enabled: true
    lease:
      duration: 5
    enabled: true  # false value disables discovery request.

externals:
  iwomi:
    apiKeys:
      momo: "5e016fb8-ef10-458c-80c4-442e94708eee"
      om: "36f4b65b-bbcf-4ca6-b881-1ba76b95ac39"
    apiSecrets:
      momo: "6ef3965f-ccb9-4f70-8864-1ca1de8e7c7d"
      om: "0cf40e83-e3eb-4bc1-9504-8d6cd3878343"
    username: "iwomipay2021"
    password: "iwomipay@2020"
  base-url:
    auth: http://localhost:8080/api/v1/auth
    iwomiPay: https://www.pay.iwomitechnologies.com/api/iwomipay_sandbox

logging:
  level:
    org:
      springframework:
        messaging: DEBUG
        web:
          socket:
            messaging: DEBUG

#    com.example.howtodoinjava: DEBUG
